// <auto-generated />
using System;
using Collector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collector.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Collector.Models.ChangeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgSid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType");

                    b.HasIndex("UserHandle");

                    b.HasIndex("OrgSid", "Timestamp");

                    b.ToTable("change_events", (string)null);
                });

            modelBuilder.Entity("Collector.Models.DiscoveredOrganization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlCorpo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sid")
                        .IsUnique();

                    b.ToTable("discovered_organizations", (string)null);
                });

            modelBuilder.Entity("Collector.Models.MemberCollectionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgSid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("UserHandle");

                    b.HasIndex("OrgSid", "CollectionTime");

                    b.ToTable("member_collection_log", (string)null);
                });

            modelBuilder.Entity("Collector.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Charter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContentCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusPrimaryImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusPrimaryName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusSecondaryImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusSecondaryName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manifesto")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Recruiting")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Roleplay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlCorpo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Sid");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Sid", "Timestamp")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Collector.Models.OrganizationMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("OrgSid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("UserHandle");

                    b.HasIndex("OrgSid", "IsActive");

                    b.HasIndex("OrgSid", "Timestamp");

                    b.HasIndex("OrgSid", "UserHandle");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("Collector.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CitizenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Enlisted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("UserHandle");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Collector.Models.UserEnrichmentQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enriched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserHandle")
                        .IsUnique()
                        .HasDatabaseName("IX_user_enrichment_queue_UserHandle_Pending")
                        .HasFilter("\"Enriched\" = 0");

                    b.HasIndex("Enriched", "Priority", "QueuedAt");

                    b.ToTable("user_enrichment_queue", (string)null);
                });

            modelBuilder.Entity("Collector.Models.UserHandleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CitizenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("UserHandle");

                    b.ToTable("user_handle_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
